#!/bin/sh

# Builds the site in the current repository

set -e

# Remember to always use "local" time formats in git commands!
export TZ="UTC0"

ENGINE_PATH="$(dirname "$0")"
SITE_PATH="$(readlink -f "$ENGINE_PATH/..")"
SRC_PATH="$SITE_PATH/src"
CSS_PATH="$SITE_PATH/css"

PAGE_TEMPLATE="$ENGINE_PATH/page.html"
NAV_TEMPLATE="$ENGINE_PATH/nav-item.html"
CSS_ITEM_TEMPLATE="$ENGINE_PATH/stylesheet.html"

INDEX_TEMPLATE="$ENGINE_PATH/index-content.html"
INDEX_ITEM_TEMPLATE="$ENGINE_PATH/index-item.html"
INDEX_HISTORY_ITEM_TEMPLATE="$ENGINE_PATH/index-history-item.html"

RESERVED_NAMES="src|engine|css|README"

page_name() {
	basename "$1" | cut -d. -f1
}

reserved_name() {
	page_name "$1" \
		| grep -xE "$RESERVED_NAMES" >/dev/null
}

index_name() {
	[ "$(page_name "$1")" = "index" ]
}

site_rel_path() {
	echo "$1" | sed "s|^$SITE_PATH||"
}

# Check environment
PANDOC="$(which pandoc || echo -n)"

ext_to_converter() {
	case "$1" in
		"html")
			echo -n 'cat'
			;;

		"md")
			if [ -z "$PANDOC" ]; then
				echo "ERROR: Pandoc must be installed to use markdown" >&2
				return 1
			fi

			echo -n "$PANDOC -f markdown-smart -t html"
			;;

		*)
			echo "WARNING: Unknown file type $extension" >&2
			return 0
			;;
	esac
}


# Derive site-wide parameters
capitalise() {
	read val
	echo -n "$val" | head -c1 | tr [:lower:] [:upper:]
	echo -n "$val" | tail -c+2
}


echo "# Building site"

SITE_NAME="$(
	{
		git describe --tags --first-parent --abbrev=0 2>/dev/null \
		|| git symbolic-ref --short HEAD 2>/dev/null \
		|| echo -n "Unnamed website"
	} \
	| sed 's/-/ /g' \
	| capitalise
)"
echo "$SITE_NAME"


echo "## Prepopulating page template"

SITE_PAGE_TEMPLATE="$(mktemp)"
echo "$SITE_PAGE_TEMPLATE"

cat "$PAGE_TEMPLATE" \
	| sed -e "s/<SITE-NAME>/$SITE_NAME/g" \
	> "$SITE_PAGE_TEMPLATE"


echo "### Building main navigation"

build_pages_nav() {
	for page_file in "$SRC_PATH"/*; do
		reserved_name "$page_file" && continue
		index_name "$page_file" && continue

		name="$(page_name "$page_file")"
		url="/$name"
		title="$(echo "$name" | capitalise)"

		cat "$NAV_TEMPLATE" \
			| sed -e "s|<URL>|$url|g" \
				-e "s|<TITLE>|$title|g"
	done
}

build_pages_nav \
	| sed -i -e "/<PAGES-NAVIGATION>/ { r /dev/stdin" -e ';d};' \
		"$SITE_PAGE_TEMPLATE"


echo "## Removing previous files"
cd "$SITE_PATH"
for extant in *; do
	reserved_name "$extant" && continue

	rm -rfv "$extant"
done


echo "## Generating pages"

site_path() {
	source_path="$1"

	rel_path="$(echo "$source_path" | sed -e "s|^$SRC_PATH/\?||")"
	readlink -m "$SITE_PATH/$rel_path"
}

page_path() {
	source_file="$1"

	name="$(page_name "$source_file")"
	rel_path="$(dirname "$source_file" | sed -e "s|^$SRC_PATH/\?||")"

	if [ "index" = "$name" ]; then
		readlink -m "$SITE_PATH/$rel_path"
	else
		readlink -m "$SITE_PATH/$rel_path/$name"
	fi
}

sub_page_vars() (
	input_file="$1"

	## NB. Using --reverse neuters --follow, so we tail instead
	date_created="$(git log --follow --author-date-order --date=local --pretty=format:"%as" -- "$input_file" | tail -n1)"
	date_updated="$(git log --follow -n1 --author-date-order --date=local --pretty=format:"%as" -- "$input_file")"

	sed \
		-e "s/<SITE-NAME>/$SITE_NAME/g" \
		-e "s/<DATE-CREATED>/$date_created/g" \
		-e "s/<DATE-UPDATED>/$date_updated/g" \
		</dev/stdin
)


build_history_items() (
	source_path="$1"

	git log --follow --date=format-local:"%Y-%m-%d %H:%M:%SZ" --pretty=tformat:"%H%x09%h%x09%ad%x09%s" -- "$source_path" \
		| while read -r line; do
			longhash="$(echo "$line" | cut -f1)"
			shorthash="$(echo "$line" | cut -f2)"
			date="$(echo "$line" | cut -f3)"
			subject="$(echo "$line" | cut -f4-)"
			cat "$INDEX_HISTORY_ITEM_TEMPLATE" \
				| sed \
					-e "s|<LONGHASH>|$longhash|g" \
					-e "s|<SHORTHASH>|$shorthash|g" \
					-e "s|<DATE>|$date|g" \
					-e "s|<SUBJECT>|$subject|g"
		done
)

build_history() (
	source_path="$1"

	reserved_name "$source_path" && return 0

	echo "#### History page"

	output_path="$(page_path "$source_path")"
	rel_output_path="$(site_rel_path "$output_path")"
	if [ -z "$rel_output_path" ]; then
		rel_output_path="/"
	fi

	mkdir -p "$output_path"

	build_history_items "$source_path" \
		| sed -e "/<INDEX-ITEMS>/ { r /dev/stdin" -e ';d};' \
			-e "s|<INDEX-TITLE>|$rel_output_path|g" \
			"$INDEX_TEMPLATE" \
		| sed -e "/<PAGE-CONTENT>/ { r /dev/stdin" -e ';d};' \
			"$SITE_PAGE_TEMPLATE" \
		| sub_css \
		| sub_page_vars "$source_path" \
		> "$output_path/history.html"
)


sub_css() (
	indent=""
	while IFS= read -r line; do
		if echo "$line" | grep '<STYLESHEETS>' >/dev/null; then
			indent="$(echo "$line" | sed -e 's/<STYLESHEETS>.*$//')"
			break
		fi
		echo "$line"
	done

	for source_file in "$CSS_PATH"/*; do
		stylesheet="$(site_rel_path "$source_file")"
		echo -n "$indent"
		cat "$CSS_ITEM_TEMPLATE" \
			| sed \
				-e "s|<URL>|$stylesheet|g"
	done

	while IFS= read -r line; do
		echo "$line"
	done
)


build_file() (
	input_file="$1"

	reserved_name "$input_file" && return 0

	output_path="$(page_path "$input_file")"
	output_index="$output_path/index.html"
	
	rel_output_path="$(site_rel_path "$output_path")"
	if index_name "$input_file"; then
		rel_output_path="$rel_output_path/index"
	fi
	echo "### $rel_output_path"

	mkdir -p "$output_path"

	extension="$(basename "$input_file" | cut -d. -f2)"
	converter="$(ext_to_converter "$extension")"

	if [ -n "$converter" ]; then
		pages_navigation="$(build_pages_nav)"

		cat "$input_file" \
			| $converter \
			| sed -e "/<PAGE-CONTENT>/ { r /dev/stdin" -e ';d};' \
				"$SITE_PAGE_TEMPLATE" \
			| sub_css \
			| sub_page_vars "$input_file" \
			> "$output_index"

		build_history "$input_file"
	fi
)


build_dir_index_items() (
	source_path="$1"

	for source_file in "$source_path"/*; do
		reserved_name "$source_file" && continue

		output_path="$(page_path "$source_file")"
		url="$(site_rel_path "$output_path")"
		title="$(basename "$output_path" | capitalise)"

		cat "$INDEX_ITEM_TEMPLATE" \
			| sed -e "s|<URL>|$url|g" \
				-e "s|<TITLE>|$title|g"
	done
)

build_dir_index() (
	source_path="$1"

	rel_path="$(echo "$source_path" | sed -e "s|^$SRC_PATH/\?||")"
	dir_name="$(basename "$rel_path" | capitalise)"
	output_path="$(site_path "$source_path")"

	rel_output_path="$(site_rel_path "$output_path")"
	echo "### $rel_output_path/index"

	build_dir_index_items "$source_path" \
		| sed -e "/<INDEX-ITEMS>/ { r /dev/stdin" -e ';d};' \
			-e "s/<INDEX-TITLE>/$dir_name/g" \
			"$INDEX_TEMPLATE" \
		| sed -e "/<PAGE-CONTENT>/ { r /dev/stdin" -e ';d};' \
			"$SITE_PAGE_TEMPLATE" \
		| sub_css \
		| sub_page_vars "$source_path" \
		> "$output_path/index.html"

	build_history "$source_path"
)

build_dir() (
	source_path="$1"
	indexed=""

	for source_file in "$source_path"/*; do
		if [ -d "$source_file" ]; then
			build_dir "$source_file"
		else
			if index_name "$source_file"; then
				indexed="yup"
			fi
			build_file "$source_file"
		fi
	done

	if [ -z "$indexed" ]; then
		build_dir_index "$source_path"
	fi
)

build_dir "$SRC_PATH"


echo "## Removing temporary files"
rm "$SITE_PAGE_TEMPLATE"
